<?php

/**
 * @file
 * Islandora docs solution pack module
 */

/**
 * Register the solution pack
 * @param type $data 
 */
function islandora_docs_sp_register_solution_pack()
{
    // Name the solution pack
     return array( 'islandora_docs_sp' => 'Islandora Documents Solution Pack' );
}

/**
 * Register the solution pack forms
 * @param array $data
 * @return type 
 */
function islandora_docs_sp_register_solution_pack_forms()
{
    // Get the module path
    $module_path = drupal_get_path('module', 'islandora_docs_sp');

    // Return the forms
    return array( 'islandora_docs_sp' =>
        array(
            'label' => 'Islandora Docs MODS Form',
            'file' => "$module_path/xml/mods_article.xml",
        ),
    );
}

/**
 * Register the solution packs content models
 * @param type $data 
 */
function islandora_docs_sp_register_solution_pack_content_models()
{
    // Get the module path
    $module_path = drupal_get_path('module', 'islandora_docs_sp');

    // Return the content models
    return array( 'islandora_docs_sp' =>
        array(
            'pid' => 'islandora:docs_sp_cm',
            'label' => 'Islandora Document Content Model',
            'form' => 'Islandora Docs MODS Form',
            'dsid' => 'ISLANDORACM',
            'datastream_file' => "$module_path/xml/docs_content_model.xml",
        ),
    );
}

/**
 * Register the solution packs content models
 * @param type $data 
 */
function islandora_docs_sp_register_solution_pack_collection()
{
    // Get the module path
    $module_path = drupal_get_path('module', 'islandora_docs_sp');
    
    // Return the collections
    return array( 'islandora_docs_sp' =>
        array(
            'pid' => 'islandora:docs_sp_collection',
            'label' => 'Islandora Document Collection',
            'cmodel' => 'islandora:collectionCModel',
            'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
            'dsid' => 'COLLECTION_POLICY',
            'datastream_file' => "$module_path/xml/docs_collection.xml",
            'thumbnail_file' =>  "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
            'thumbnail_mimetype' => 'image/png',
        ),
    );        
}

/**
 * SP Hook: Set the solution pack defaults 
 * @param type $data
 * @return string 
 */
function islandora_docs_sp_setup_defaults(&$data)
{
    
    // Create an area for this solution pack
    $data['islandora_docs_sp'] = array(
        'label' => 'Islandora Documents Solution Pack',
        'forms' => array(

        ), 
        'objects' => array(
            array(
                'pid' => 'islandora:docs_sp_cm',
                'label' => 'Islandora Document Content Model',
                'form' => 'Islandora Docs MODS Form',
                'dsid' => 'ISLANDORACM',
                'datastream_file' => "$module_path/xml/docs_content_model.xml",
            ), 
            array(
                'pid' => 'islandora:docs_sp_collection',
                'label' => 'Islandora Document Collection',
                'cmodel' => 'islandora:collectionCModel',
                'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
                'datastreams' => array(
                    array(
                        'dsid' => 'TN',
                        'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
                        'mimetype' => 'image/png',
                    ),
                    array(
                        'dsid' => 'COLLECTION_POLICY',
                        'datastream_file' => "$module_path/xml/docs_collection.xml",
                    ),
                ),
            ),
        ),
    );
    
    // Return the config
    return $data;
}


