<?php

/**
 * @file
 * Islandora docs solution pack module
 */

/**
 * islandora pdf sp required fedora objects
 * @return type 
 */
function islandora_docs_sp_required_fedora_objects() {

    // Get the module name and path name
    $module_name = explode('.module',basename(__FILE__));
    $module_name = $module_name[0];
    
    // Get the path
    $module_path = drupal_get_path('module', $module_name);
    
    // User defined values
    $module_title = 'Islandora Documents Solution Pack';    

    $form_name = 'Islandora Documents MODS Form';
    $form_xml_file = "$module_path/xml/mods_article.xml";
    
    $content_model = 'islandora:docs_sp_content_model';
    $content_model_label = 'Islandora Document Content Model'; 
    $content_model_file = "$module_path/xml/docs_content_model.xml";
    
    $collection = 'islandora:docs_sp_collection';
    $collection_label = 'Islandora Document Collection';
    $collection_file = "$module_path/xml/docs_collection.xml";
    $collection_thumbnail_file = "$module_path/images/Crystal_Clear_filesystem_folder_grey.png";
    $collection_thumbnail_mimetype = 'image/png';

    // Include the solution pack
    module_load_include('inc', 'fedora_repository', 'fedora_repository.solutionpacks');
    
    // Add the forms
    solution_pack_add_form($form_name, file_get_contents($form_xml_file));
    solution_pack_add_form_association($content_model, $form_name);

    return array(
    $module_name => array(
      'module' => $module_name,
      'title' => $module_title,
      'objects' => array(
        array(
          'pid' => $content_model,
          'label' => $content_model_label,
          'dsid' => 'ISLANDORACM',
          'datastream_file' => $content_model_file,
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'pid' => $collection,
          'label' => $collection_label,
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => $collection_thumbnail_file,
              'mimetype' => $collection_thumbnail_mimetype,
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => $collection_file,
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * Register Disseminators and Viewers
 * @return type 
 */
function islandora_docs_sp_register_services()
{
    // Define the end points
    return array(
        'islandora_docs_sp' => array (
            'pdf' => array (
                'title' => 'PDF', 
                'function' => 'pdf_handler', 
                'param_count' => 1, 
                'security' => array('access content'),
                'render_drupal' => false, 
                'example' => 'pdf/{pid}',
            ),
            'thumbnail' => array (
                'title' => 'Thumbnail',
                'function' => 'thumbnail_handler',
                'param_count' => 1,
                'security' => array('access content'),
                'render_drupal' => false, 
                'example' => 'thumbnail/{pid}'
            ),
            'view' => array (
                'title' => 'PDF Viewer',
                'function' => 'view_handler',
                'param_count' => 1,
                'security' => array('access content'),
                'render_drupal' => true,
                'example' => 'view/{pid}'
            ),
            'viewer' => array (
                'title' => 'Flexpaper',
                'function' => 'view_swf',
                'param_count' => 0,
                'security' => array('access content'),
                'render_drupal' => false,
                'example' => 'viewer',
            ),
        )
    );
}

/**
 * PDF endpoint
 * @param type $pid
 * @return type 
 */
function islandora_docs_sp_pdf_handler($pid) {

    module_load_include('inc', 'fedora_repository', 'fedora_respository');
    return makeObject($pid, 'OBJ');
}

/**
 * Thumbnail endpoint
 * @param type $pid
 * @return type 
 */
function islandora_docs_sp_thumbnail_handler($pid) {

    module_load_include('inc', 'fedora_repository', 'fedora_respository');
    return makeObject($pid, 'TN');
}

/**
 * Viewer 
 * @param type $pid
 */
function islandora_docs_sp_view_handler($pid) {

    // Add swfobject
    drupal_add_js(drupal_get_path('module', 'islandora_docs_sp') . '/viewer/flexpaper_flash.js');
    
    // Get drupals base url
    global $base_url;

    $doc = $base_url . '/islandora_services/islandora_docs_sp/pdf/' . $pid;
    $content = '<iframe src="http://docs.google.com/viewer?url='.$doc.'&embedded=true" width="600" height="780" style="border: none;"></iframe>';
    
    // Return the render data
    return $content;
}

/**
 * Load and pass through the viewer
 * @param type $type 
 */
/*
function islandora_docs_sp_view_swf($type) {

    // Create a file handler to the player
    $fileHandler = fopen(drupal_get_path('module', 'islandora_docs_sp') . '/viewer/FlexPaperViewer.swf',"r");
    
    // Set the header to shockwave
    header("Content-type: application/x-shockwave-flash");
    header("Content-Length: " . filesize($fileHandler));    
    
    // Psss the binary to the browser
    fpassthru($fileHandler);
    exit();
}
*/




